---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-custom
subjects:
  - kind: ServiceAccount
    namespace: openshift-operators
    name: argocd-argocd-application-controller
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
